### ISSUE TITLE
softPwmCreate,softPwmWrite is not working as expected

### ISSUE THREAD

**Issue by vtumi** [WiringPi/WiringPi-PHP#14]
if  value > 1 or value <100
these would be the wrong
wiringpi::softPwmCreate(0, value, 100)
wiringpi::softPwmWrite(0, value);

work
wiringpi::softPwmCreate(0, 0, 100)
wiringpi::softPwmWrite(0, 100);
usleep(10000)

not work
wiringpi::softPwmCreate(0, 0, 100)
wiringpi::softPwmWrite(0, 100);

i can't find the problem

**Comment by Gadgetoid** [comment]
Ahoy! Sorry I haven't had a moment to look into this yet. Are you closing because you found a solution? Would be handy to know if the documentation could be changed ( or in this case, created ) to make it clearer.

Cheers

**Comment by vtumi** [comment]
The error message is segmentation fault.
I am using C language to use wiringPi now.
It works better.
